[package]
name    = "publisher"
version = "0.0.1"

authors     = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
description = "Tool to publish & distribute CLI tools"
homepage    = "https://github.com/termapps/publisher"
repository  = "https://github.com/termapps/publisher"

edition      = "2021"
rust-version = "1.67.0"

categories = ["command-line-utilities"]
license    = "MIT"
readme     = "README.md"

[dependencies]
clap                = { version = "~4.1.8", features = ["derive", "wrap_help"] }
clap-verbosity-flag = "~2.0.0"
concolor-clap       = { version = "0.0.14", features = ["api_unstable"] }

xshell = "~0.2.3"

[[bin]]
name = "publisher"
path = "src/main.rs"

[profile.release]
lto = "thin"

[workspace.metadata.workspaces]
no_individual_tags = true
