name = "publisher"

description = "Tool to publish & distribute CLI tools"
homepage    = "https://github.com/termapps/publisher"
license     = "MIT"
repository  = "termapps/publisher"

[aur]
repository = "publisher-git"

[aur_bin]
repository = "publisher"

[homebrew]
repository = "termapps/homebrew-tap"
