name = "publisher"

description = "Tool to publish & distribute CLI tools"
homepage    = "https://github.com/termapps/publisher"
license     = "MIT"
repository  = "termapps/publisher"

exclude = ["aur"]

[homebrew]
repository = "termapps/homebrew-tap"
